"""empty message

Revision ID: 0afaa60e08f6
Revises: b60bb67d1758
Create Date: 2021-05-09 16:45:21.323344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0afaa60e08f6'
down_revision = 'b60bb67d1758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('guidelines', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'guidelines')
    # ### end Alembic commands ###
