"""empty message

Revision ID: 0b2eafb6f289
Revises: b60bb67d1758
Create Date: 2021-04-25 17:55:27.859122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2eafb6f289'
down_revision = 'b60bb67d1758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('time_tracked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'time_tracked')
    # ### end Alembic commands ###
