"""empty message

Revision ID: 3c792bab8903
Revises: b60bb67d1758
Create Date: 2021-05-02 10:10:30.420177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c792bab8903'
down_revision = 'b60bb67d1758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('tracked_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'tracked_time')
    # ### end Alembic commands ###
